version: "3.0"
services:
  nginx:
    image: nginx:alpine
    container_name: vps_nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d/:/etc/nginx/conf.d/:ro"
      - "./nginx/logs/:/var/log/nginx/"
      - "../vps-nginx-acme/letsencrypt/etc:/etc/letsencrypt:ro"
      - "../vps-nginx-acme/letsencrypt/etc:/etc/nginx/certs:ro"
    restart: always
networks:
  default:
    external:
      name: vps-nginx-reverse-proxy
